envs:
  global:
    variables:
      ELECTRODE_BUILD_URL: https://18041b6190de461274b48dd40fc75c7c5f8eac53@gecgithub01.walmart.com/api/v3/repos/electrode-ops/build/contents/bootstrap.sh?ref=master
checkoutDir: repo

tools:
  nodejs:
    - 8.16.1
  sonarscanner: 4.1.0.1829

trigger:
  pr:
    - call: unit-test
    - call: run-sonar-pr

flows:
  default:
    - call: electrode_build
    - call: sonar
  test:
    - npm install
    - npm test
  sonar:
    - sonar("Sonar"): |
        sonar-scanner -X -Dproject.settings=sonar-project.properties -Dsonar.projectKey=brand-portal
        - hygieia.publishSonar()
  run-sonar-pr:
    - sonar("Sonar"):
        sonar-scanner -X -Dproject.settings=sonar-project.properties
        -Dsonar.projectKey=brand-portal
        -Dsonar.pullrequest.github.repository=RET-Marketplace/brand-portal
        -Dsonar.pullrequest.key=${GITHUB_PR_NUMBER}
        -Dsonar.pullrequest.branch=${GITHUB_PR_SOURCE_BRANCH}
        -Dsonar.pullrequest.base=${GITHUB_PR_TARGET_BRANCH}
        -Dsonar.scm.revision=${GITHUB_PR_HEAD_SHA}

  electrode_build:
    - shell (name electrode_build): |
        curl -H "Accept: application/vnd.github.VERSION.raw" "${ELECTRODE_BUILD_URL}" | bash
