inherit: "job://electrode_looper-flows:.looper.yml"

tools:
  nodejs: 8.16.1
  sonarscanner: 4.2.0.1873

checkoutDir: repo



envs:
  global:
    variables:
      ELECTRODE_BUILD_URL: https://18041b6190de461274b48dd40fc75c7c5f8eac53@gecgithub01.walmart.com/api/v3/repos/electrode-ops/build/contents/bootstrap.sh?ref=master

flows:
  default:
    - call: electrode_build
    - call: sonar
  sonar:
    - sonar("Sonar"):
    - (name sonar) sonar-scanner -Dproject.settings=repo/sonar-project.properties
    - hygieia.publishBuild()
    - hygieia.publishSonar()


#flows:
#  default:
#    - call: electrode_build
#    - call: sonar
#  sonar:
#    - sonar("Sonar"):
#        - (name sonar) sonar-scanner -X -Dsonar.projectKey=brand-portal
#          -Dproject.settings=sonar-project.properties
#        - hygieia.publishSonar()
#
#  electrode_build:
#    - shell (name electrode_build): |
#        curl -H "Accept: application/vnd.github.VERSION.raw" "${ELECTRODE_BUILD_URL}" | bash
#  pr:
#    - call: electrode_pr
#    - call: sonar
