inherit: "job://electrode_looper-flows:.looper.yml"

tools:
  nodejs: 8.16.1
  sonarscanner: 4.2.0.1873

checkoutDir: repo

flows:
  default:
    - call: electrode_build
    - call: sonar
  release-build:
    - call: electrode_build
    - call: sonar
  pr:
    - echo "$GITHUB_PR_URL"
    - call: electrode_pr
    - call: sonar-fetch-remote-fix-ref
    - call: sonar
  snapshot-build:
      - echo "$GITHUB_PR_URL"
      - call: electrode_pr
      - call: sonar-fetch-remote-fix-ref
      - call: sonar

  sonar-fetch-origin:
    shell (silent): |
      #!/bin/bash
      git fetch --no-tags origin ${GITHUB_BRANCH_NAME}:refs/remotes/origin/${GITHUB_BRANCH_NAME}

  sonar-fetch-origin-fix-ref:
    shell (silent): |
      #!/bin/bash
      git fetch --no-tags origin ${GITHUB_PR_TARGET_BRANCH}:refs/remotes/origin/${GITHUB_PR_TARGET_BRANCH}
      git checkout -b remotes/origin/pr/${GITHUB_PR_NUMBER}
      git branch -D ${GITHUB_PR_TARGET_BRANCH}

  sonar:
    - sonar("Sonar"):
        - (name Sonar For PR) sonar-scanner -X -Dsonar.projectKey=brand-portal -Dproject.settings=repo/sonar-project.properties -Dsonar.pullrequest.base=${GITHUB_PR_TARGET_BRANCH} -Dsonar.pullrequest.branch=${GITHUB_PR_SOURCE_BRANCH} -Dsonar.pullrequest.github.repository=RET-Marketplace/brand-portal -Dsonar.pullrequest.key=${GITHUB_PR_NUMBER} -Dsonar.scm.revision=${GITHUB_PR_HEAD_SHA}

#  sonar:
#    - sonar("Sonar"):
#      - (name sonar) sonar-scanner -Dsonar.projectKey=brand-portal
#          -Dproject.settings=repo/sonar-project.properties
#          -Dsonar.pullrequest.github.repository=RET-Marketplace/brand-portal
#          -Dsonar.pullrequest.key=${GITHUB_PR_NUMBER}
#          -Dsonar.pullrequest.branch=${GITHUB_PR_SOURCE_BRANCH}
#          -Dsonar.pullrequest.base=${GITHUB_PR_TARGET_BRANCH}
#          -Dsonar.scm.revision=${GITHUB_PR_HEAD_SHA}
#    - hygieia.publishSonar()
