inherit: "job://electrode_looper-flows:.looper.yml"

tools:
  nodejs: 8.16.1
  sonarscanner: 4.2.0.1873

checkoutDir: repo

flows:
  default:
    - call: electrode_build
    - call: sonar
  pr:
    - call: electrode_pr
    - call: sonar
  sonar:
    - sonar("Sonar"):
        - (name sonar) sonar-scanner -X -Dsonar.projectKey=brand-portal -Dproject.settings=repo/sonar-project.properties
        - hygieia.publishSonar()
