envs:
  global:
    variables:
      ELECTRODE_BUILD_URL: https://18041b6190de461274b48dd40fc75c7c5f8eac53@gecgithub01.walmart.com/api/v3/repos/electrode-ops/build/contents/bootstrap.sh?ref=master
checkoutDir: repo

tools:
  nodejs:
    - 8.16.1
  sonarscanner: 4.1.0.1829

flows:
  default:
    - call: electrode_build
    - call: sonar
  sonar:
    - sonar("Sonar"):
        - (name sonar) sonar-scanner -X -Dsonar.projectKey=brand-portal
          -Dsonar.projectName=brand-portal
          -Dsonar.projectVersion=1.0.1
          -Dsonar.sources=src
          -Dsonar.tests=src
          -Dsonar.test.inclusions=src/**/*test.js
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.testExecutionReportPaths=test_report.xml
          -Dsonar.host.url=https://sonar.wal-mart.com
          -Dsonar.branch.name=dev/sonarIntegration
          -Dproject.settings=sonar-project.properties
        - hygieia.publishSonar()

  electrode_build:
    - shell (name electrode_build): |
        curl -H "Accept: application/vnd.github.VERSION.raw" "${ELECTRODE_BUILD_URL}" | bash
