
const MIXPANEL_CONSTANTS = {
    LOGIN: {
        USER_LOGIN: "LOGIN_SUCCESS"
    },
    LOGOUT: {
        USER_LOGOUT: "LOGOUT"
    },
    COMPANY_REGISTRATION: {
        CREATE_COMPANY_PROFILE: "CREATE_COMPANY_PROFILE",
        RESET_COMPANY_PROFILE: "CANCLE_ONBOARDING_FORM",
        BRAND_REGISTRATION: "BRAND_REGISTRATION",
        COMPANY_ONBOARDING_DETAIL_SUBMISSION: "ONBOARDING_DETAIL_SUBMISSION"
    },
    VALIDATION_EVENTS: {
        CHECK_COMPANY_NAME_AVIAILIBILITY: "COMPANY_NAME_AVAILABILITY_CHECK",
        CHECK_BRAND_UNIQUENESS: "BRAND_UNIQUENESS_CHECK",
        CHECK_TRADEMARK_AVAILIBITY: "TRADEMARK_VALIDITY",
        CHECK_EMAIL_AVAILIBITY: "EMAIL_VALIDITY_CHECK"
    },
    CLAIM_LIST_WORKFLOW: {
        VIEW_CLAIMS: "VIEW_CLAIMS",
        VIEW_CLAIM_DETAILS: "VIEW_CLAIM_DETAILS"
    },
    BRAND_LIST_WORKFLOW: {
        VIEW_BRANDS: "VIEW_BRANDS",
        EDIT_BRAND: "EDIT_BRAND",
        UPDATE_BRAND_STATUS: "UPDATE_BRAND_STATUS"
    },
    USER_LIST_WORKFLOW: {
        VIEW_USERS: "VIEW_USERS",
        UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
        RESEND_INVITE: "RESEND_INVITE",
        EDIT_USER_PROFILE: "EDIT_USER_PROFILE"
    },
    VIEW_DASHBOARD_WORKFLOW: {
        VIEW_DASHBOARD: "VIEW_DASHBOARD",
        FILTER_SELECTED: "FILTER_SELECTED"
    },
    FILE_UPLOAD_EVENTS: {
        FILE_UPLOAD: "UPLOAD_DOCUMENT"
    },
    NEW_CLAIM_TEMPLATE_EVENTS: {
        SUBMIT_NEW_CLAIM: "SUBMIT_NEW_CLAIM",
        GET_SELLERS_NAME: "GET_SELLERS_NAME",
        CANCEL_CLAIM_DETAILS: "CANCEL_SUBMIT_CLAIM",
        ATTEMPT_SUBMIT_CLAIM: "ATTEMPT_SUBMIT_CLAIM",
        SUBMITTED_CLAIM_DEATILS: "SUBMITTED_CLAIM_DEATILS"
    },
    NEW_BRAND_TEMPLATE_EVENTS: {
        BRAND_DETAILS_SUBMISSION: "BRAND_DETAILS_SUBMISSION",
        CANCEL_SUBMIT_BRAND_DETAILS: "CANCEL_SUBMIT_BRAND_DETAILS",
        ATTEMPT_SUBMIT_BRAND: "ATTEMPT_SUBMIT_BRAND"
    },
    INVITE_NEW_USER_TEMPLATE_EVENTS: {
        USER_DETAILS_SUBMISSION: "USER_DETAILS_SUBMISSION",
        CANCEL_SUBMIT_USER_DETAILS: "CANCEL_SUBMIT_USER_DETAILS",
        ATTEMPT_INVITE_USER: "ATTEMPT_SUBMIT_INVITE_USER"
    },
    HOME_PAGE_EVENTS: {
        WBP_HOME_PAGE: "VISIT_HOME_PAGE",
        LOGIN_CLICK_EVENT: "CLICK_ON_LOGIN",
        REGISTER_CLICK_EVENT: "CLICK_ON_REGISTER"
    },
    USER_PROFILE: {
        VIEW_USER_PROFILE: "VIEW_USER_PROFILE",
        CHANGE_PASSWORD: {
            CHANGE_USER_PASSWORD: "DISPLAY_CHANGE_PASSWORD",
            CANCLE_CHANGE_PASSWORD: "CANCEL_CHANGE_PASSWORD",
            CHANGE_PASSWORD: "CHANGE_PASSWORD"
        },
        EDIT_USER_PROFILE: {
            EDIT_USER_PROFILE: "EDIT_PROFILE",
            CANCLE_EDIT_USER_PROFILE: "CANCEL_EDIT_PROFILE",
            SAVE_USER_PROFILE: "SAVE_PROFILE"
        }
    },
    HELP_CENTER_EVENTS: {
        VIEW_HELP_MENU: "VIEW_HELP_MENU",
        VIEW_HELP_TOPICS: "VIEW_HELP_TOPICS"
    },
    ADD_NEW_TEMPLATE: {
        NewClaimTemplate: "ADD_NEW_CLAIM",
        NewBrandTemplate: "ADD_BRAND",
        CreateUserTemplate: "INVITE_NEW_USER"
    },
    WORK_FLOW_MAPPING: {
        newbrand: "ADD_NEW_BRAND",
        brandreg: "COMPANY_ONBOARDING",
        companyreg: "COMPANY_ONBOARDING",
        newuser: "INVITE_NEW_USER"
    },
    HELP_TOPIC_MAPPING: {
        loginfaq: "FREQUENTLY_ASKED_QUESTIONS",
        faq: "FREQUENTLY_ASKED_QUESTIONS",
        user: "USER_MANAGEMENT",
        brand: "USER_MANAGEMENT",
        claim: "CLAIM_SUBMISSION",
        contact: "CONTACT_US"
    },
    FILTER_SELECTED_MAPPING: {
        reportedClaimsType: "CLAIM_SUBMITTED_BY_TYPE",
        topReportedBrands: "CLAIM_SUBMITTED_BY_BRAND",
        topReporters: "CLAIM_SUBMITTED_BY_USER"
    }
};

export default MIXPANEL_CONSTANTS;
