
const MIXPANEL_CONSTANTS = {
    LOGIN: {
        LOGIN_SUCCESS: "LOGIN_SUCCESS"
    },
    LOGOUT: {
        LOGOUT: "LOGOUT"
    },
    COMPANY_REGISTRATION: {
        CREATE_COMPANY_PROFILE: "CREATE_COMPANY_PROFILE",
        CANCLE_ONBOARDING_FORM: "CANCLE_ONBOARDING_FORM",
        BRAND_REGISTRATION: "BRAND_REGISTRATION",
        ONBOARDING_DETAIL_SUBMISSION: "ONBOARDING_DETAIL_SUBMISSION"
    },
    VALIDATION_EVENTS: {
        COMPANY_NAME_AVAILABILITY_CHECK: "COMPANY_NAME_AVAILABILITY_CHECK",
        BRAND_UNIQUENESS_CHECK: "BRAND_UNIQUENESS_CHECK",
        TRADEMARK_VALIDITY: "TRADEMARK_VALIDITY",
        EMAIL_VALIDITY_CHECK: "EMAIL_VALIDITY_CHECK"
    },
    CLAIM_LIST_WORKFLOW: {
        VIEW_CLAIMS: "VIEW_CLAIMS",
        VIEW_CLAIM_DETAILS: "VIEW_CLAIM_DETAILS"
    },
    BRAND_LIST_WORKFLOW: {
        VIEW_BRANDS: "VIEW_BRANDS",
        EDIT_BRAND: "EDIT_BRAND",
        UPDATE_BRAND_STATUS: "UPDATE_BRAND_STATUS"
    },
    USER_LIST_WORKFLOW: {
        VIEW_USERS: "VIEW_USERS",
        UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
        RESEND_INVITE: "RESEND_INVITE",
        EDIT_USER_PROFILE: "EDIT_USER_PROFILE"
    },
    VIEW_DASHBOARD_WORKFLOW: {
        VIEW_DASHBOARD: "VIEW_DASHBOARD",
        FILTER_SELECTED: "FILTER_SELECTED"
    },
    FILE_UPLOAD_EVENTS: {
        UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT"
    },
    NEW_CLAIM_TEMPLATE_EVENTS: {
        SUBMIT_NEW_CLAIM: "SUBMIT_NEW_CLAIM",
        GET_SELLERS_NAME: "GET_SELLERS_NAME",
        CANCEL_SUBMIT_CLAIM: "CANCEL_SUBMIT_CLAIM",
        SUBMIT_CLAIM_CLICKED: "SUBMIT_CLAIM_CLICKED",
        SUBMITTED_CLAIM_DEATILS: "SUBMITTED_CLAIM_DEATILS"
    },
    NEW_BRAND_TEMPLATE_EVENTS: {
        BRAND_DETAILS_SUBMISSION: "BRAND_DETAILS_SUBMISSION",
        CANCEL_SUBMIT_BRAND_DETAILS: "CANCEL_SUBMIT_BRAND_DETAILS",
        SUBMIT_BRAND_CLICKED: "SUBMIT_BRAND_CLICKED"
    },
    INVITE_NEW_USER_TEMPLATE_EVENTS: {
        USER_DETAILS_SUBMISSION: "USER_DETAILS_SUBMISSION",
        CANCEL_SUBMIT_USER_DETAILS: "CANCEL_SUBMIT_USER_DETAILS",
        SUBMIT_CREATED_USER_CLICKED: "SUBMIT_CREATED_USER_CLICKED"
    },
    HOME_PAGE_EVENTS: {
        VISIT_HOME_PAGE: "VISIT_HOME_PAGE",
        CLICK_ON_LOGIN: "CLICK_ON_LOGIN",
        CLICK_ON_REGISTER: "CLICK_ON_REGISTER"
    },
    USER_PROFILE: {
        VIEW_USER_PROFILE: "VIEW_USER_PROFILE",
        CHANGE_PASSWORD: {
            DISPLAY_CHANGE_PASSWORD: "DISPLAY_CHANGE_PASSWORD",
            CANCEL_CHANGE_PASSWORD: "CANCEL_CHANGE_PASSWORD",
            CHANGE_PASSWORD: "CHANGE_PASSWORD"
        },
        EDIT_USER_PROFILE: {
            EDIT_PROFILE: "EDIT_PROFILE",
            CANCEL_EDIT_PROFILE: "CANCEL_EDIT_PROFILE",
            SAVE_PROFILE: "SAVE_PROFILE"
        }
    },
    HELP_CENTER_EVENTS: {
        VIEW_HELP_MENU: "VIEW_HELP_MENU",
        VIEW_HELP_TOPICS: "VIEW_HELP_TOPICS"
    },
    TOU_TEMPLATE: {
        TOU_VERIFICATION: "TOU_VERIFICATION"
    },
    ADD_NEW_TEMPLATE_MAPPING: {
        NewClaimTemplate: "ADD_NEW_CLAIM",
        NewBrandTemplate: "ADD_BRAND",
        CreateUserTemplate: "INVITE_NEW_USER"
    },
    WORK_FLOW_MAPPING: {
        newbrand: "ADD_NEW_BRAND",
        brandreg: "COMPANY_ONBOARDING",
        companyreg: "COMPANY_ONBOARDING",
        newuser: "INVITE_NEW_USER"
    },
    HELP_TOPIC_MAPPING: {
        loginfaq: "FREQUENTLY_ASKED_QUESTIONS",
        faq: "FREQUENTLY_ASKED_QUESTIONS",
        user: "USER_MANAGEMENT",
        brand: "USER_MANAGEMENT",
        claim: "CLAIM_SUBMISSION",
        contact: "CONTACT_US"
    },
    FILTER_SELECTED_MAPPING: {
        reportedClaimsType: "CLAIM_SUBMITTED_BY_TYPE",
        topReportedBrands: "CLAIM_SUBMITTED_BY_BRAND",
        topReporters: "CLAIM_SUBMITTED_BY_USER"
    },
    LOGOUT_WORKFLOW_MAPPING: {
        1: "PORTAL_REGISTRATION",
        2: "PORTAL_VERIFICATION",
        4: "PORTAL_DASHBOARD",
        8: "PORTAL_ACCESS_REVOKED",
        16: "USER_ACCESS_REVOKED",
        32: "REQUEST_ACCESS",
        64: "USER_VERIFICATION",
        128: "TOU_VERIFICATION"
    }
};

export default MIXPANEL_CONSTANTS;
